---
title: "Chipotle Sourcream"
author: "Sahar Mozaffari"
date: "December 16, 2015"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    theme: cosmo
    toc: yes
  pdf_document:
    toc: yes
  word_document: default
---

R Markdown for Chipotle Sourcream

If you don't have, install packages for ggplot2 and reshape2:

install.packages("ggplot2")
install.packages("reshape2") 

```{r library_load, include=FALSE}

library(ggplot2)
library(reshape2)

```



```{r bysourcream, echo=FALSE}
table <- read.table("orders.txt",  sep="\t", header = T)
tacos <- table[grep("Taco", table$item_name),]
tacos <- cbind(tacos, "taco")
colnames(tacos)[6] <- "Type"
burritos <- table[grep("Burrito", table$item_name),]
burritos <- cbind(burritos, "burrito")
colnames(burritos)[6] <- "Type"
bowls <- table[grep("Bowl", table$item_name),]
bowls <- cbind(bowls, "bowl")
colnames(bowls)[6] <- "Type"

foods <- rbind(tacos,burritos,bowls)

var <- grepl("Sour Cream", foods$choice_description)
foods <- cbind(foods, var)
colnames(foods)[7] <- "Sourcream"

ggplot(foods, aes(factor(Sourcream)))+ geom_bar(aes(fill=Type)) + scale_x_discrete(limits=c(FALSE, TRUE), labels=c("No Sourcream", "Sourcream")) + labs(x = "Sourcream or not?", title = "Sourcream at Chipotle 1")

```


```{r byfood, echo = FALSE}
food <- melt(foods, id="Type", measure="Sourcream")
ggplot(food, aes(x=Type, fill=value))+geom_bar(stat="bin", position="dodge")+labs(x = "Type of food", title = "Sourcream at Chipotle 2")+ scale_fill_discrete("Sourcream or not?", breaks=c("FALSE", "TRUE"),   labels=c("No Sourcream", "Yes Sourcream"))
```
